### ISSUE TITLE
502 Bad Gateway on Centos 8

### ISSUE THREAD

**Issue by KarlBaumann** [nginx-proxy/nginx-proxy#1529]
Is there something special we have to do to get it running on Centos 8?

I tried to run the basic docker-compose.yaml example from README
```
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
```

And I got:
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.19.3</center>
</body>
</html>
```

**Comment by mamyn0va** [comment]
Same on Debian 10 here.

**Comment by KarlBaumann** [comment]
Is this project dead? I see many issues mentioning 502 error.

**Comment by nickv2002** [comment]
I have some older containers that I configured a month or so ago and continue to work fine with this proxy. But everything I've tried to set up with this proxy over the last few weeks has this same 502 error. Very weird and not too helpful I know, but the change roughly correlates to the creation date on the newest nginx-proxy image (Created 2020-10-30 09:46:00 sha256:5e6f392e99e5454851caa8a3dbb021560a32375edff772b64f862c4d7831d038) so maybe that is related?

In any case here's the tail of the log from **nginx-proxy** for while I try to access the proxy:

> today at 10:38 AM Custom dhparam.pem file found, generation skipped
> today at 10:38 AM forego     | starting dockergen.1 on port 5000
> today at 10:38 AM forego     | starting nginx.1 on port 5100
> today at 10:38 AM dockergen.1 | 2020/11/03 18:38:28 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
> today at 10:38 AM dockergen.1 | 2020/11/03 18:38:28 Watching docker events
> today at 10:38 AM dockergen.1 | 2020/11/03 18:38:28 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
> today at 10:39 AM dockergen.1 | 2020/11/03 18:39:26 Received event die for container ee889cabfcd8
> today at 10:39 AM dockergen.1 | 2020/11/03 18:39:26 Received event stop for container ee889cabfcd8
> today at 10:39 AM dockergen.1 | 2020/11/03 18:39:26 Generated '/etc/nginx/conf.d/default.conf' from 11 containers
> today at 10:39 AM dockergen.1 | 2020/11/03 18:39:26 Running 'nginx -s reload'
> today at 10:39 AM dockergen.1 | 2020/11/03 18:39:26 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
> today at 10:39 AM dockergen.1 | 2020/11/03 18:39:27 Received event die for container 2dadf9c97119
> today at 10:39 AM dockergen.1 | 2020/11/03 18:39:27 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
> today at 10:39 AM dockergen.1 | 2020/11/03 18:39:27 Received event start for container 2dadf9c97119
> today at 10:39 AM dockergen.1 | 2020/11/03 18:39:27 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
> today at 10:40 AM dockergen.1 | 2020/11/03 18:40:29 Received event start for container 5fbff26b8d87
> today at 10:40 AM dockergen.1 | 2020/11/03 18:40:29 Generated '/etc/nginx/conf.d/default.conf' from 12 containers
> today at 10:40 AM dockergen.1 | 2020/11/03 18:40:30 Received event die for container 2dadf9c97119
> today at 10:40 AM dockergen.1 | 2020/11/03 18:40:30 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
> today at 10:40 AM dockergen.1 | 2020/11/03 18:40:31 Received event start for container 2dadf9c97119
> today at 10:40 AM dockergen.1 | 2020/11/03 18:40:31 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
> today at 10:40 AM nginx.1    | 2020/11/03 18:40:41 [error] 42#42: *1 no live upstreams while connecting to upstream, client: 172.18.0.1, server: twldev.local, request: "GET / HTTP/1.1", upstream: "http://twldev.local/", host: "twldev.local"
> today at 10:40 AM nginx.1    | twldev.local 172.18.0.1 - - [03/Nov/2020:18:40:41 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
> today at 10:40 AM nginx.1    | 2020/11/03 18:40:41 [error] 42#42: *2 no live upstreams while connecting to upstream, client: 172.18.0.1, server: twldev.local, request: "GET /favicon.ico HTTP/1.1", upstream: "http://twldev.local/favicon.ico", host: "twldev.local", referrer: "http://twldev.local/"
> today at 10:40 AM nginx.1    | twldev.local 172.18.0.1 - - [03/Nov/2020:18:40:41 +0000] "GET /favicon.ico HTTP/1.1" 502 157 "http://twldev.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"

Looks like the mDNS cname has been setup but nginx can't connect to the container.

Any idea what is going on and how I could fix things?
Thanks again!

**Comment by mamyn0va** [comment]
Hi, here is what I got 

```
❯ docker-compose logs nginx-proxy | more                                                                                                                                                    22:05:15
Attaching to nginx-proxy
nginx-proxy                | WARNING: /etc/nginx/dhparam/dhparam.pem was not found. A pre-generated dhparam.pem will be used for now while a new one
nginx-proxy                | is being generated in the background.  Once the new dhparam.pem is in place, nginx will be reloaded.
nginx-proxy                | forego     | starting dockergen.1 on port 5000
nginx-proxy                | forego     | starting nginx.1 on port 5100
nginx-proxy                | dockergen.1 | 2020/11/17 22:04:37 Generated '/etc/nginx/conf.d/default.conf' from 4 containers
nginx-proxy                | dockergen.1 | 2020/11/17 22:04:37 Running 'nginx -s reload'
nginx-proxy                | dockergen.1 | 2020/11/17 22:04:37 Watching docker events
nginx-proxy                | dockergen.1 | 2020/11/17 22:04:37 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy                | nginx.1    | 2020/11/17 22:04:45 [error] 80#80: *1 no live upstreams while connecting to upstream, client: 90.46.166.58, server: plop.fr, request: "GET / HTTP/2.0", upstream: "http://plop.fr/", host: "plop.fr"
nginx-proxy                | nginx.1    | plop.fr 90.46.166.58 - - [17/Nov/2020:22:04:45 +0000] "GET / HTTP/2.0" 502 157 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"
nginx-proxy                | nginx.1    | 2020/11/17 22:04:50 [error] 80#80: *1 no live upstreams while connecting to upstream, client: 90.46.166.58, server: plop.fr, request: "GET / HTTP/2.0", upstream: "http://plop.fr/", host: "plop.fr"
nginx-proxy                | nginx.1    | plop.fr 90.46.166.58 - - [17/Nov/2020:22:04:50 +0000] "GET / HTTP/2.0" 502 157 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:78
.0) Gecko/20100101 Firefox/78.0"
```

**Comment by dahoba** [comment]
Did you try to enabling masquerading in CentOS 8?

**Comment by KarlBaumann** [comment]
> Did you try to enabling masquerading in CentOS 8?

I did not. I just switched to Traefik.

**Comment by Hamsterman** [comment]
> > Did you try to enabling masquerading in CentOS 8?
> 
> I did not. I just switched to Traefik.

That looks like a good replacement - what is your experience with it so far ?

**Comment by KarlBaumann** [comment]
> That looks like a good replacement - what is your experience with it so far ?
It is very powerful, but also a bit tricky to configure.

**Comment by buchdag** [comment]
This might have been fixed by #1601 

@mamyn0va, @nickv2002, care to test ?

**Comment by nickv2002** [comment]
I pulled the latest image with sha256:`7e3a002124fc0221b7952f761ec34d6e68fb5c626b4a047c395e5fac1b4fcc93` but still get the 502 errors I was before - no change in behavior:
```
today at 11:25:44 AM  nginx.1    | 2021/04/26 18:25:44 [error] 40#40: *15 no live upstreams while connecting to upstream, client: 10.0.1.32, server: mylar.local, request: "GET / HTTP/1.1", upstream: "http://mylar.local/", host: "mylar.local"
today at 11:25:44 AM  nginx.1    | mylar.local 10.0.1.32 - - [26/Apr/2021:18:25:44 +0000] "GET / HTTP/1.1" 502 157 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
```

**Comment by buchdag** [comment]
Could you post the output of those commands ?

```
docker inspect yournginxproxycontainer
docker exec yournginxproxycontainer nginx -T
docker exec yournginxproxycontainer cat /proc/1/cpuset
docker exec yournginxproxycontainer cat /proc/self/cgroup
docker exec yournginxproxycontainer cat /proc/self/mountinfo
```

**Comment by nickv2002** [comment]
A long dump of text from my nginx container
```docker inspect 4f3c9e8cd81e

[
    {
        "Id": "4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376",
        "Created": "2021-04-27T04:08:43.793336301Z",
        "Path": "/app/docker-entrypoint.sh",
        "Args": [
            "forego",
            "start",
            "-r"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2265760,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-04-27T04:08:44.708808588Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:6026622ddd3c0347725f0b740a84c97f71b46bb60f9aa9c6868b3f0430e1cbad",
        "ResolvConfPath": "/var/lib/docker/containers/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376/hostname",
        "HostsPath": "/var/lib/docker/containers/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376/hosts",
        "LogPath": "/var/lib/docker/containers/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376-json.log",
        "Name": "/nginx-proxy",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "1e7ae4fb689aacb2ddc06409cf5cd19d2ebc30b5fc47131d67b31bcaf8dbbae3:/etc/nginx/dhparam",
                "/var/run/docker.sock:/tmp/docker.sock:ro",
                "c9011d52b83b60af42bf83866849776b1e080fab6a7418803b6d798d122774eb:/etc/nginx/certs"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "compose_default",
            "PortBindings": {
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [
                "AUDIT_WRITE",
                "CHOWN",
                "DAC_OVERRIDE",
                "FOWNER",
                "FSETID",
                "KILL",
                "MKNOD",
                "NET_BIND_SERVICE",
                "NET_RAW",
                "SETFCAP",
                "SETGID",
                "SETPCAP",
                "SETUID",
                "SYS_CHROOT"
            ],
            "CapDrop": [
                "AUDIT_CONTROL",
                "BLOCK_SUSPEND",
                "DAC_READ_SEARCH",
                "IPC_LOCK",
                "IPC_OWNER",
                "LEASE",
                "LINUX_IMMUTABLE",
                "MAC_ADMIN",
                "MAC_OVERRIDE",
                "NET_ADMIN",
                "NET_BROADCAST",
                "SYSLOG",
                "SYS_ADMIN",
                "SYS_BOOT",
                "SYS_MODULE",
                "SYS_NICE",
                "SYS_PACCT",
                "SYS_PTRACE",
                "SYS_RAWIO",
                "SYS_RESOURCE",
                "SYS_TIME",
                "SYS_TTY_CONFIG",
                "WAKE_ALARM"
            ],
            "CgroupnsMode": "host",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/1ac1e534adaecb7f29c6b1ef9077b73c4ae2de6c433ceab63e124a13843656a9-init/diff:/var/lib/docker/overlay2/a6bc6d69984480eaf63e2de3e09a0a0e04a1638b8902c7455dfa4ac51b383444/diff:/var/lib/docker/overlay2/059d1402807018d6d5855864860fb16f490f7b25623ea4f0e479dbaa326f5d6f/diff:/var/lib/docker/overlay2/67d1ab60e61b62d7b5f12d1a5042078be988905153ffd43f7ef2ae102d1357f2/diff:/var/lib/docker/overlay2/f62cc620d5b4bc8b7e2d6b2e1545877859595885d3841d5a7c5c43eb0522903f/diff:/var/lib/docker/overlay2/2f71f994a9c6cb46887505fceac9a6f0c1be7ba32d06efb00fa6674faa0145ee/diff:/var/lib/docker/overlay2/bcd7c6ed7f2355b04aba9b4252e0fff3da7be7e1f65daa369bd5688e79a5e878/diff:/var/lib/docker/overlay2/e65cea776c32beacb5d588ee6b6278e0de8bc96c5e6ddba4dc25c0cec3eb287b/diff:/var/lib/docker/overlay2/299490a8936d769934d43fad063a68a2da70d3464e93648ab1e00de20980d276/diff:/var/lib/docker/overlay2/689557072f8cbc612958bb3b4d699768aeb7860cea55c04b4ba90684d6fcaf38/diff:/var/lib/docker/overlay2/00f181a3d890a5f69fea65ee202361eee657017f1147c75c8ecc8ac60e8c98e2/diff:/var/lib/docker/overlay2/3943fa787eba1b5037b7e99d85c032c9f957d91f56ac40b392af3679d91ceb8e/diff:/var/lib/docker/overlay2/2b45b493b3d3dc219cef757ab3905ab8f7c7021dba1d5ee042e8c7c4a417f846/diff",
                "MergedDir": "/var/lib/docker/overlay2/1ac1e534adaecb7f29c6b1ef9077b73c4ae2de6c433ceab63e124a13843656a9/merged",
                "UpperDir": "/var/lib/docker/overlay2/1ac1e534adaecb7f29c6b1ef9077b73c4ae2de6c433ceab63e124a13843656a9/diff",
                "WorkDir": "/var/lib/docker/overlay2/1ac1e534adaecb7f29c6b1ef9077b73c4ae2de6c433ceab63e124a13843656a9/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "c9011d52b83b60af42bf83866849776b1e080fab6a7418803b6d798d122774eb",
                "Source": "/var/lib/docker/volumes/c9011d52b83b60af42bf83866849776b1e080fab6a7418803b6d798d122774eb/_data",
                "Destination": "/etc/nginx/certs",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "1e7ae4fb689aacb2ddc06409cf5cd19d2ebc30b5fc47131d67b31bcaf8dbbae3",
                "Source": "/var/lib/docker/volumes/1e7ae4fb689aacb2ddc06409cf5cd19d2ebc30b5fc47131d67b31bcaf8dbbae3/_data",
                "Destination": "/etc/nginx/dhparam",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/var/run/docker.sock",
                "Destination": "/tmp/docker.sock",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "2d044818d783",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "DOCKER_GEN_VERSION=0.7.4",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NGINX_VERSION=1.19.10",
                "NJS_VERSION=0.5.3",
                "PKG_RELEASE=1~buster",
                "DOCKER_HOST=unix:///tmp/docker.sock"
            ],
            "Cmd": [
                "forego",
                "start",
                "-r"
            ],
            "Image": "jwilder/nginx-proxy:latest",
            "Volumes": {
                "/etc/nginx/certs": {},
                "/etc/nginx/dhparam": {},
                "/tmp/docker.sock": {}
            },
            "WorkingDir": "/app",
            "Entrypoint": [
                "/app/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "maintainer": "Jason Wilder mail@jasonwilder.com",
                "org.opencontainers.image.created": "2021-04-26T00:31:18.590Z",
                "org.opencontainers.image.description": "Automated nginx proxy for Docker containers using docker-gen",
                "org.opencontainers.image.licenses": "MIT",
                "org.opencontainers.image.revision": "eac17ac03cf162e56c87a4959c740fb746ac1094",
                "org.opencontainers.image.source": "https://github.com/nginx-proxy/nginx-proxy",
                "org.opencontainers.image.title": "nginx-proxy",
                "org.opencontainers.image.url": "https://github.com/nginx-proxy/nginx-proxy",
                "org.opencontainers.image.version": "latest"
            },
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "3c4fdd0c60ce136b1cc8aa2ab144c2e4082cc68290faad10b21e9061b26fd38a",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "80"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/3c4fdd0c60ce",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "compose_default": {
                    "IPAMConfig": {},
                    "Links": null,
                    "Aliases": [
                        "24788e65fbc1",
                        "2d044818d783",
                        "9c7934906177",
                        "e7e4a1d69d7e",
                        "d2223a09233e",
                        "648574df9110",
                        "e2d3d812f459",
                        "1d8d60236c70",
                        "e9c5280fa021",
                        "73cf0550da38",
                        "8b5b76edd5d2",
                        "4f3c9e8cd81e"
                    ],
                    "NetworkID": "9ab568e76d17176e1fcb4139c4aa10ef380af0117305fa91f4c2af2881f97064",
                    "EndpointID": "bbebc629f3053bd4772e8b862f4c324964e3a2cf7c41307c74682bc6ae7d3847",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:04",
                    "DriverOpts": null
                }
            }
        }
    }
]
---------------------
docker exec 4f3c9e8cd81e nginx -T

nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
# configuration file /etc/nginx/nginx.conf:

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}
daemon off;

# configuration file /etc/nginx/mime.types:

types {
    text/html                                        html htm shtml;
    text/css                                         css;
    text/xml                                         xml;
    image/gif                                        gif;
    image/jpeg                                       jpeg jpg;
    application/javascript                           js;
    application/atom+xml                             atom;
    application/rss+xml                              rss;

    text/mathml                                      mml;
    text/plain                                       txt;
    text/vnd.sun.j2me.app-descriptor                 jad;
    text/vnd.wap.wml                                 wml;
    text/x-component                                 htc;

    image/png                                        png;
    image/svg+xml                                    svg svgz;
    image/tiff                                       tif tiff;
    image/vnd.wap.wbmp                               wbmp;
    image/webp                                       webp;
    image/x-icon                                     ico;
    image/x-jng                                      jng;
    image/x-ms-bmp                                   bmp;

    font/woff                                        woff;
    font/woff2                                       woff2;

    application/java-archive                         jar war ear;
    application/json                                 json;
    application/mac-binhex40                         hqx;
    application/msword                               doc;
    application/pdf                                  pdf;
    application/postscript                           ps eps ai;
    application/rtf                                  rtf;
    application/vnd.apple.mpegurl                    m3u8;
    application/vnd.google-earth.kml+xml             kml;
    application/vnd.google-earth.kmz                 kmz;
    application/vnd.ms-excel                         xls;
    application/vnd.ms-fontobject                    eot;
    application/vnd.ms-powerpoint                    ppt;
    application/vnd.oasis.opendocument.graphics      odg;
    application/vnd.oasis.opendocument.presentation  odp;
    application/vnd.oasis.opendocument.spreadsheet   ods;
    application/vnd.oasis.opendocument.text          odt;
    application/vnd.openxmlformats-officedocument.presentationml.presentation
                                                     pptx;
    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
                                                     xlsx;
    application/vnd.openxmlformats-officedocument.wordprocessingml.document
                                                     docx;
    application/vnd.wap.wmlc                         wmlc;
    application/x-7z-compressed                      7z;
    application/x-cocoa                              cco;
    application/x-java-archive-diff                  jardiff;
    application/x-java-jnlp-file                     jnlp;
    application/x-makeself                           run;
    application/x-perl                               pl pm;
    application/x-pilot                              prc pdb;
    application/x-rar-compressed                     rar;
    application/x-redhat-package-manager             rpm;
    application/x-sea                                sea;
    application/x-shockwave-flash                    swf;
    application/x-stuffit                            sit;
    application/x-tcl                                tcl tk;
    application/x-x509-ca-cert                       der pem crt;
    application/x-xpinstall                          xpi;
    application/xhtml+xml                            xhtml;
    application/xspf+xml                             xspf;
    application/zip                                  zip;

    application/octet-stream                         bin exe dll;
    application/octet-stream                         deb;
    application/octet-stream                         dmg;
    application/octet-stream                         iso img;
    application/octet-stream                         msi msp msm;

    audio/midi                                       mid midi kar;
    audio/mpeg                                       mp3;
    audio/ogg                                        ogg;
    audio/x-m4a                                      m4a;
    audio/x-realaudio                                ra;

    video/3gpp                                       3gpp 3gp;
    video/mp2t                                       ts;
    video/mp4                                        mp4;
    video/mpeg                                       mpeg mpg;
    video/quicktime                                  mov;
    video/webm                                       webm;
    video/x-flv                                      flv;
    video/x-m4v                                      m4v;
    video/x-mng                                      mng;
    video/x-ms-asf                                   asx asf;
    video/x-ms-wmv                                   wmv;
    video/x-msvideo                                  avi;
}

# configuration file /etc/nginx/conf.d/default.conf:
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
		ssl_protocols TLSv1.2 TLSv1.3;
		ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
		ssl_prefer_server_ciphers off;
resolver 127.0.0.11;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
	server_name _; # This is just an invalid value which will never trigger on a real hostname.
	listen 80;
	access_log /var/log/nginx/access.log vhost;
	return 503;
}
# dozzle.local
upstream dozzle.local {
				## Can be connected with "compose_default" network
			# dozzle
			server 172.18.0.7:8080;
}
server {
	server_name dozzle.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://dozzle.local;
	}
}
# mylar.local
upstream mylar.local {
				# Cannot connect to network of this container
				server 127.0.0.1 down;
}
server {
	server_name mylar.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://mylar.local;
	}
}
# registry.local
upstream registry.local {
				# Cannot connect to network of this container
				server 127.0.0.1 down;
}
server {
	server_name registry.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://registry.local;
	}
}
# speedtest.local
upstream speedtest.local {
				## Can be connected with "compose_default" network
			# speedtest
			server 172.18.0.5:80;
}
server {
	server_name speedtest.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://speedtest.local;
	}
}
# twl.local
upstream twl.local {
				# Cannot connect to network of this container
				server 127.0.0.1 down;
}
server {
	server_name twl.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://twl.local;
	}
}
# yacreader-server.local
upstream yacreader-server.local {
				## Can be connected with "compose_default" network
			# YACReaderServer
			server 172.18.0.6:8080;
}
server {
	server_name yacreader-server.local;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://yacreader-server.local;
	}
}

---------------------
docker exec 4f3c9e8cd81e cat /proc/1/cpuset

/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
---------------------
docker exec 4f3c9e8cd81e cat /proc/self/cgroup

12:cpu,cpuacct:/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
11:blkio:/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
10:freezer:/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
9:pids:/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
8:perf_event:/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
7:hugetlb:/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
6:devices:/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
5:net_cls,net_prio:/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
4:rdma:/
3:cpuset:/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
2:memory:/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
1:name=systemd:/docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376
0::/system.slice/containerd.service
---------------------
docker exec 4f3c9e8cd81e cat /proc/self/mountinfo

2388 1543 0:79 / / rw,relatime master:117 - overlay overlay rw,lowerdir=/var/lib/docker/overlay2/l/YQZONBMT6ASKUAM6VJCM2E3DIQ:/var/lib/docker/overlay2/l/LYTW7RNVQSJ7UFLJSMPSJRWAIR:/var/lib/docker/overlay2/l/CADU45NECKM5FCALAXTBLA2PX3:/var/lib/docker/overlay2/l/OBWIY7AJG4NSEUEIW7QQQ5K3VZ:/var/lib/docker/overlay2/l/7M74JY4R46HXO65P3234VFJXHP:/var/lib/docker/overlay2/l/BDNYO7IA3QVIGJTZTLLPW6AJ4P:/var/lib/docker/overlay2/l/3H4A4RO2NB7OGLTAPKMKPTSCXP:/var/lib/docker/overlay2/l/DCNAZCSSMMQMFAO6BQLN6NGWWV:/var/lib/docker/overlay2/l/R6OBYC5KRS4X2GMO6SBLPLNUK2:/var/lib/docker/overlay2/l/LO4FRELKS4HLKHIGDFMV2AYACX:/var/lib/docker/overlay2/l/QR5I5NDP7WCSMLPM3OAE5PHMKF:/var/lib/docker/overlay2/l/2HOEAUNE2N5MMHFPHNVHHREQKI:/var/lib/docker/overlay2/l/U73GJVPVNMZXSUAANKWIIT5DZJ,upperdir=/var/lib/docker/overlay2/1ac1e534adaecb7f29c6b1ef9077b73c4ae2de6c433ceab63e124a13843656a9/diff,workdir=/var/lib/docker/overlay2/1ac1e534adaecb7f29c6b1ef9077b73c4ae2de6c433ceab63e124a13843656a9/work
2389 2388 0:151 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
2390 2388 0:152 / /dev rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
2391 2390 0:153 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666
2392 2388 0:154 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs ro
2393 2392 0:155 / /sys/fs/cgroup rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,mode=755
2394 2393 0:30 /docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376 /sys/fs/cgroup/systemd ro,nosuid,nodev,noexec,relatime master:11 - cgroup cgroup rw,xattr,name=systemd
2395 2393 0:34 /docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376 /sys/fs/cgroup/memory ro,nosuid,nodev,noexec,relatime master:16 - cgroup cgroup rw,memory
2396 2393 0:35 /docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376 /sys/fs/cgroup/cpuset ro,nosuid,nodev,noexec,relatime master:17 - cgroup cgroup rw,cpuset
2397 2393 0:36 / /sys/fs/cgroup/rdma ro,nosuid,nodev,noexec,relatime master:18 - cgroup cgroup rw,rdma
2398 2393 0:37 /docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376 /sys/fs/cgroup/net_cls,net_prio ro,nosuid,nodev,noexec,relatime master:19 - cgroup cgroup rw,net_cls,net_prio
2399 2393 0:38 /docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376 /sys/fs/cgroup/devices ro,nosuid,nodev,noexec,relatime master:20 - cgroup cgroup rw,devices
2400 2393 0:39 /docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376 /sys/fs/cgroup/hugetlb ro,nosuid,nodev,noexec,relatime master:21 - cgroup cgroup rw,hugetlb
2401 2393 0:40 /docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376 /sys/fs/cgroup/perf_event ro,nosuid,nodev,noexec,relatime master:22 - cgroup cgroup rw,perf_event
2402 2393 0:41 /docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376 /sys/fs/cgroup/pids ro,nosuid,nodev,noexec,relatime master:23 - cgroup cgroup rw,pids
2403 2393 0:42 /docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376 /sys/fs/cgroup/freezer ro,nosuid,nodev,noexec,relatime master:24 - cgroup cgroup rw,freezer
2404 2393 0:43 /docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376 /sys/fs/cgroup/blkio ro,nosuid,nodev,noexec,relatime master:25 - cgroup cgroup rw,blkio
2407 2393 0:44 /docker/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376 /sys/fs/cgroup/cpu,cpuacct ro,nosuid,nodev,noexec,relatime master:26 - cgroup cgroup rw,cpu,cpuacct
2408 2390 0:150 / /dev/mqueue rw,nosuid,nodev,noexec,relatime - mqueue mqueue rw
2409 2390 0:156 / /dev/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,size=65536k
2410 2388 0:25 /docker.sock /tmp/docker.sock ro,relatime - tmpfs tmpfs rw,size=2450176k,mode=755
2411 2388 8:66 /var/lib/docker/containers/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376/resolv.conf /etc/resolv.conf rw,relatime - ext4 /dev/sde2 rw,errors=remount-ro
2412 2388 8:66 /var/lib/docker/containers/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376/hostname /etc/hostname rw,relatime - ext4 /dev/sde2 rw,errors=remount-ro
2413 2388 8:66 /var/lib/docker/containers/4f3c9e8cd81e7d89933b45d9b9fd948729de929b174e02647a12a28fb6168376/hosts /etc/hosts rw,relatime - ext4 /dev/sde2 rw,errors=remount-ro
2414 2388 8:66 /var/lib/docker/volumes/1e7ae4fb689aacb2ddc06409cf5cd19d2ebc30b5fc47131d67b31bcaf8dbbae3/_data /etc/nginx/dhparam rw,relatime master:1 - ext4 /dev/sde2 rw,errors=remount-ro
2416 2388 8:66 /var/lib/docker/volumes/c9011d52b83b60af42bf83866849776b1e080fab6a7418803b6d798d122774eb/_data /etc/nginx/certs rw,relatime master:1 - ext4 /dev/sde2 rw,errors=remount-ro
1544 2389 0:151 /bus /proc/bus ro,relatime - proc proc rw
1545 2389 0:151 /fs /proc/fs ro,relatime - proc proc rw
1546 2389 0:151 /irq /proc/irq ro,relatime - proc proc rw
1547 2389 0:151 /sys /proc/sys ro,relatime - proc proc rw
1548 2389 0:151 /sysrq-trigger /proc/sysrq-trigger ro,relatime - proc proc rw
1549 2389 0:181 / /proc/acpi ro,relatime - tmpfs tmpfs ro
1550 2389 0:152 /null /proc/kcore rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
1551 2389 0:152 /null /proc/keys rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
1552 2389 0:152 /null /proc/timer_list rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
1553 2389 0:152 /null /proc/sched_debug rw,nosuid - tmpfs tmpfs rw,size=65536k,mode=755
1862 2389 0:182 / /proc/scsi ro,relatime - tmpfs tmpfs ro
1863 2392 0:183 / /sys/firmware ro,relatime - tmpfs tmpfs ro
---------------------
```

**Comment by nickv2002** [comment]
A long dump of text from those commands
[output.txt](https://github.com/nginx-proxy/nginx-proxy/files/6395243/output.txt)

**Comment by buchdag** [comment]
Are you certain the mylar.local container is sharing a network with the nginx-proxy (or docker-gen if you use a two container setup) container ?

```
docker inspect --format='{{.NetworkSettings.Networks}}' yournginxproxycontainer
docker inspect --format='{{.NetworkSettings.Networks}}' mylar.localcontainer
```

**Comment by nickv2002** [comment]
> Are you certain the mylar.local container is sharing a network with the nginx-proxy (or docker-gen if you use a two container setup) container ?
> 
> ```
> docker inspect --format='{{.NetworkSettings.Networks}}' yournginxproxycontainer
> docker inspect --format='{{.NetworkSettings.Networks}}' mylar.localcontainer
> ```

Ahh so they're on different networks... hmm. Must be related to having different docker-compose stacks for them in my case.
```
nick@uzfs:~$ docker inspect --format='{{.NetworkSettings.Networks}}' 6f745d600817
map[bridge:0xc000535b00]
nick@uzfs:~$ docker inspect --format='{{.NetworkSettings.Networks}}' 4f3c9e8cd81e
map[compose_default:0xc000576000]```
Thanks for you help debugging that. I'll work on figuring out how to bridge that networking unless you have any tips offhand.

**Comment by buchdag** [comment]
I usually create a separate Docker network outside of Docker compose then use it as an external network in the compose file.

```
docker network create nginx-proxy
```

then

```yaml
version: '3'

services:
  nginx:
    [...]
    networks:
      nginx-proxy:

# Do not forget to 'docker network create nginx-proxy' before launch
# and to connect the proxied containers to the nginx-proxy network.

networks:
  nginx-proxy:
    external: true
```

Repeated in every compose file for services that will be proxied.

Also take a look at https://github.com/buchdag/letsencrypt-nginx-proxy-companion-compose
